export default {
	'Material': [
		'Gray Brick',
		'Stone & Timbers',
		'Cut Stone Blocks',
		'Wooden Boards',
		'Plaster Board & Timbers',
		'Metal Sheeting',
	],

	'Exterior Detail': [
		'Tile Work',
		'Iron Work',
		'Glass Work',
		'Stone Work',
		'Wood Work',
		'Landscaping',
	],

	'Use': [
		'Bunk House',
		'Inn',
		'Tavern',
		'Gambling Hall',
		'Drug Den',
		'Brothel',
		'Market',
		'Workshop',
		'Bakery',
		'Butchery',
		'Forge',
		'Tailory',
		'Work House',
		'Goat Stables',
		'Brewery',
		'Watch Post',
		'Court, Jail',
		'Dock',
		'Ruin',
		'Row Houses',
		'Tenements',
		'Apartment Building',
		'Small House',
		'Bath House',
		'Shrine',
		'Tattooist',
		'Physicker',
		'Fighting Pits',
		'Square, Fountain',
		'Grotto',
		'Warehouse',
		'Stockyard',
		'Factory',
		'Refinery',
		'Eelery',
		'Mushroom Garden',
	],

	'Use (Rare)': [
		'Market House',
		'Restaurant',
		'Bar, Lounge',
		'Academy',
		'Salon',
		'Cafe',
		'Floristry',
		'Tobacconist',
		'Book Shop',
		'Jeweler',
		'Clothier',
		'Gallery',
		'Apothecary',
		'Horse Stables',
		'Distillery',
		'Vintner',
		'Master Artisan',
		'Boat House',
		'Theater',
		'Opera House',
		'Apartment Building',
		'Townhouse',
		'Manor House',
		'Villa',
		'Clinic',
		'Temple',
		'Cistern',
		'Watch Post',
		'Park',
		'Monument',
		'Archive',
		'Spiritualist',
		'Bank',
		'Alchemist',
		'Power Plant',
		'Radiant Energy Garden',
	],

	'Interior Detail': [
		'Dripping Water',
		'Creaking Floorboards',
		'Roaring Fires',
		'Smoky Lamps',
		'Buzzing Electric Lights',
		'Ticking Clockworks',
		'Plants, Flowers',
		'Wall Hangings, Artwork',
		'Shuttered Windows',
		'Heavy Curtains, Thick Carpet',
		'Dust, Detritus',
		'Wear, Damage',
		'Threadbare, Tattered',
		'Utilitarian Furnishings',
		'Elegant Finery',
		'Lush, Comfortable',
		'Rough-Spun Simplicity',
		'Spartan Austerity',
		'Circular Stairs, Ladders',
		'Secret Doors',
		'Catwalks',
		'Skylights',
		'Balcony',
		'Cellar5',
		'Drafty, Cold',
		'Stout, Quiet',
		'Cozy, Warm',
		'Vaulted, Spacious',
		'Low, Cramped',
		'Rickety, Ramshackle',
		'Strange Devices',
		'Weird Artifacts',
		'Spirit Wards, Old Runes',
		'Piled Jumble of Curios',
		'Antique Appointments',
		'Shrine, Altar',
	]
}